services:
  - type: web
    name: biologist-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn biologist_project.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: biologist_project.settings
      - key: PYTHON_VERSION
        value: 3.11
